In [1]:
import pandas as pd

df_military_expense = pd.read_excel('SIPRI-Milex-data-1949-2022.xlsx', sheet_name = 'Share of GDP')

df_military_expense = pd.melt(df_military_expense, id_vars=['Country', 'Notes'], var_name='Year', value_name='Military Expenditure in GDP')

df_military_expense['Year'] = pd.to_numeric(df_military_expense['Year'])

df_military_expense = df_military_expense[(df_military_expense['Year'] >= 1970) & (df_military_expense['Year'] <= 2018)]

df_military_expense = df_military_expense.drop(columns='Notes')

In [2]:
import pycountry

def get_country_code(Country):
    try:
        if Country == 'Congo, DR':
                return 'COD'
        elif Country == 'Congo, Republic':
                return 'COG'
        elif Country == "Cote d'Ivoire":
                return 'CIV'
        elif Country == 'Gambia, The':
                return 'GMB'
        elif Country == 'Korea, North':
                return 'PRK'
        elif Country == 'Korea, South':
                return 'KOR'
        elif Country == 'Kyrgyz Republic':
                return 'KGZ'
        elif Country == 'Timor Leste':
                return 'TLS'
        elif Country == 'Viet Nam':
                return 'VNM'
        elif Country == 'Türkiye':
                return 'TUR'
        elif Country == 'Yemen, North' or Country == 'Yemen':
                return 'YEM'
        elif Country == "Myanmar (Burma)":
                return 'MMR'
        elif Country == 'Russia':
                return 'RUS'
        elif Country == 'DR Congo (Zaire)':
                return 'COD'
        elif Country == 'Syria':
                return 'SYA'
        elif Country == 'Ivory Coast':
                return 'CIV'
        elif Country == 'Tanzania':
                return 'TZA'
        elif Country == 'United States of America':
                return 'USA'
        elif Country == 'Yemen (North Yemen)':
                return 'YEM'
        elif Country == 'Iran':
                return 'IRN'
        elif Country == 'Bosnia-Herzegovina':
                return 'BIH'
        elif Country == 'Laos':
                return 'LAO'
        elif Country == 'Serbia (Yugoslavia)':
                return 'SRB'
        elif Country == 'Moldova':
                return 'MDA'
        elif Country == 'Venezuela':
                return 'VEN'
        elif Country == 'Cambodia (Kampuchea)':
                return 'KHM'
        elif Country == 'Madagascar (Malagasy)':
                return 'MDG'
        elif Country == 'Zimbabwe (Rhodesia)':
                return 'ZWE'
        elif Country == 'Cape Verde':
                return "CPV"
        elif Country == 'Bolivia':
                return "BOL"
        elif Country == 'Taiwan':
                return "TWN"
        elif Country == 'Brunei':
                return "BRN"
        elif Country == 'Czechoslovakia':
                return "CSK"
        elif Country == 'German Democratic Republic':
                return "DEU"
        elif Country == 'Kosovo':
                return "XKX"
        elif Country == 'Yugoslavia':
                return 'SFR'
        elif Country == 'USSR':
                return 'SUN'
        else: 
            return pycountry.countries.get(name=Country).alpha_3
#             return pycountry.countries.search_fuzzy(Country)[0].alpha_3
    except:
        return None

In [3]:
df_military_expense['Country Code'] = df_military_expense['Country'].apply(get_country_code)

In [5]:
df_military_expense.to_csv('military_expense.csv')

In [4]:
df_military_expense

                    Country  Year Military Expenditure in GDP Country Code
3654                Algeria  1970                    0.021305          DZA
3655                  Libya  1970                    0.060729          LBY
3656                Morocco  1970                     0.02316          MAR
3657                Tunisia  1970                    0.015617          TUN
3658                 Angola  1970                         xxx          AGO
...                     ...   ...                         ...          ...
12175                 Syria  2018                         ...          SYA
12176               Türkiye  2018                    0.025237          TUR
12177  United Arab Emirates  2018                         ...          ARE
12178          Yemen, North  2018                         xxx          YEM
12179                 Yemen  2018                         ...          YEM

[8526 rows x 4 columns]